name: Check Quality Code

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      uses: actions/setup-java@v3
    - name: Run test
      run: mvn test 
